
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xae\x14)\xce ;\xb2\xd0\xbc/\xd7U\x11\x9d\xe7l'
    
_lr_action_items = {'WORD':([0,2,3,4,5,11,13,15,17,18,],[2,2,2,2,2,2,2,2,2,2,]),'H2':([0,18,],[3,3,]),'H3':([0,18,],[4,4,]),'H1':([0,18,],[5,5,]),'BLANK':([2,3,4,5,6,10,22,],[-12,11,13,15,17,17,17,]),'CR':([2,6,7,8,9,10,12,14,16,19,20,21,22,23,],[-12,-11,18,-10,-2,-14,-6,-8,-4,-7,-9,-5,-13,-3,]),'$end':([1,2,6,7,8,9,10,12,14,16,19,20,21,22,23,],[0,-12,-11,-1,-10,-2,-14,-6,-8,-4,-7,-9,-5,-13,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'body':([0,],[1,]),'text':([0,2,3,4,5,11,13,15,17,18,],[6,10,6,6,6,6,6,6,22,6,]),'expression':([0,18,],[9,23,]),'statement':([0,],[7,]),'factor':([0,3,4,5,11,13,15,18,],[8,12,14,16,19,20,21,8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> body","S'",1,None,None,None),
  ('body -> statement','body',1,'p_body','C:\\work\\work\\study\\\xb1\xe0\xd2\xeb\xd4\xad\xc0\xed_\xb8\xdf\xd5\xe4\\SSE-Compiling-Course\\ProjectTemplate\\sample\\part\\mkyacc.py',13),
  ('statement -> expression','statement',1,'p_state','C:\\work\\work\\study\\\xb1\xe0\xd2\xeb\xd4\xad\xc0\xed_\xb8\xdf\xd5\xe4\\SSE-Compiling-Course\\ProjectTemplate\\sample\\part\\mkyacc.py',17),
  ('statement -> statement CR expression','statement',3,'p_state','C:\\work\\work\\study\\\xb1\xe0\xd2\xeb\xd4\xad\xc0\xed_\xb8\xdf\xd5\xe4\\SSE-Compiling-Course\\ProjectTemplate\\sample\\part\\mkyacc.py',18),
  ('expression -> H1 factor','expression',2,'p_exp_cr_1','C:\\work\\work\\study\\\xb1\xe0\xd2\xeb\xd4\xad\xc0\xed_\xb8\xdf\xd5\xe4\\SSE-Compiling-Course\\ProjectTemplate\\sample\\part\\mkyacc.py',25),
  ('expression -> H1 BLANK factor','expression',3,'p_exp_cr_1','C:\\work\\work\\study\\\xb1\xe0\xd2\xeb\xd4\xad\xc0\xed_\xb8\xdf\xd5\xe4\\SSE-Compiling-Course\\ProjectTemplate\\sample\\part\\mkyacc.py',26),
  ('expression -> H2 factor','expression',2,'p_exp_cr_2','C:\\work\\work\\study\\\xb1\xe0\xd2\xeb\xd4\xad\xc0\xed_\xb8\xdf\xd5\xe4\\SSE-Compiling-Course\\ProjectTemplate\\sample\\part\\mkyacc.py',33),
  ('expression -> H2 BLANK factor','expression',3,'p_exp_cr_2','C:\\work\\work\\study\\\xb1\xe0\xd2\xeb\xd4\xad\xc0\xed_\xb8\xdf\xd5\xe4\\SSE-Compiling-Course\\ProjectTemplate\\sample\\part\\mkyacc.py',34),
  ('expression -> H3 factor','expression',2,'p_exp_cr3','C:\\work\\work\\study\\\xb1\xe0\xd2\xeb\xd4\xad\xc0\xed_\xb8\xdf\xd5\xe4\\SSE-Compiling-Course\\ProjectTemplate\\sample\\part\\mkyacc.py',41),
  ('expression -> H3 BLANK factor','expression',3,'p_exp_cr3','C:\\work\\work\\study\\\xb1\xe0\xd2\xeb\xd4\xad\xc0\xed_\xb8\xdf\xd5\xe4\\SSE-Compiling-Course\\ProjectTemplate\\sample\\part\\mkyacc.py',42),
  ('expression -> factor','expression',1,'p_exp_cr','C:\\work\\work\\study\\\xb1\xe0\xd2\xeb\xd4\xad\xc0\xed_\xb8\xdf\xd5\xe4\\SSE-Compiling-Course\\ProjectTemplate\\sample\\part\\mkyacc.py',49),
  ('factor -> text','factor',1,'p_factor_text','C:\\work\\work\\study\\\xb1\xe0\xd2\xeb\xd4\xad\xc0\xed_\xb8\xdf\xd5\xe4\\SSE-Compiling-Course\\ProjectTemplate\\sample\\part\\mkyacc.py',53),
  ('text -> WORD','text',1,'p_text_word','C:\\work\\work\\study\\\xb1\xe0\xd2\xeb\xd4\xad\xc0\xed_\xb8\xdf\xd5\xe4\\SSE-Compiling-Course\\ProjectTemplate\\sample\\part\\mkyacc.py',57),
  ('text -> text BLANK text','text',3,'p_text_word','C:\\work\\work\\study\\\xb1\xe0\xd2\xeb\xd4\xad\xc0\xed_\xb8\xdf\xd5\xe4\\SSE-Compiling-Course\\ProjectTemplate\\sample\\part\\mkyacc.py',58),
  ('text -> WORD text','text',2,'p_text_word','C:\\work\\work\\study\\\xb1\xe0\xd2\xeb\xd4\xad\xc0\xed_\xb8\xdf\xd5\xe4\\SSE-Compiling-Course\\ProjectTemplate\\sample\\part\\mkyacc.py',59),
]
